BINANCE_ENDPOINTS = {
    ("spot", "ohlcv"): ("api/v3/klines", ("interval", "limit")),
    ("spot", "trades"): ("api/v3/trades", ("limit",)),
    ("spot", "aggregated_trades"): ("api/v3/aggTrades", ("limit",)),
    ("spot", "order_book"): ("api/v3/depth", ("limit",)),
    ("spot", "best_bid_ask"): ("api/v3/ticker/bookTicker", ()),
    ("spot", "24hr"): ("api/v3/ticker/24hr", ()),
    ("spot", "exchangeInfo"): ("api/v3/exchangeInfo", ()),
    ("future", "ohlcv"): ("fapi/v1/klines", ("interval", "limit")),
    ("future", "trades"): ("fapi/v1/trades", ("limit",)),
    ("future", "aggregated_trades"): ("fapi/v1/aggTrades", ("limit",)),
    ("future", "order_book"): ("fapi/v1/depth", ("limit",)),
    ("future", "best_bid_ask"): ("fapi/v1/ticker/bookTicker", ()),
    ("future", "24hr"): ("fapi/v1/ticker/24hr", ()),
    ("future", "fundingRate"): ("fapi/v1/fundingRate", ("limit",)),
    ("future", "openInterest"): ("fapi/v1/openInterest", ()),
    ("future", "premiumIndex"): ("fapi/v1/premiumIndex", ()),
    ("future", "openInterestHist"): ("futures/data/openInterestHist", ("period", "limit")),
    ("future", "longShortRatio"): ("futures/data/globalLongShortAccountRatio", ("period", "limit")),
    ("future", "topLongShortAccountRatio"): ("futures/data/topLongShortAccountRatio", ("period", "limit")),
    ("future", "topLongShortPositionRatio"): ("futures/data/topLongShortPositionRatio", ("period", "limit")),
}

BINANCE_INTERVAL_MS = {
    "1s": 1_000,
    "1m": 60_000,
    "5m": 300_000,
    "15m": 900_000,
    "30m": 1_800_000,
    "1h": 3_600_000,
    "2h": 7_200_000,
    "4h": 14_400_000,
    "6h": 21_600_000,
    "8h": 28_800_000,
    "12h": 43_200_000,
    "1d": 86_400_000,
    "3d": 259_200_000,
    "1w": 604_800_000,
    "1M": 2_592_000_000,
}

__all__ = ["BINANCE_ENDPOINTS", "BINANCE_INTERVAL_MS"]
